### ISSUE TITLE
请问这个怎么用呀？新手不太会

### ISSUE THREAD

**Issue by dnxbice** [XgzK/QL_variable#1]
RT

**Comment by XgzK** [comment]
> RT

下载了放到服务器上，修改conn.yml文件的第2、3、7行
第7行你你填你的青龙IP:端口
第2、3行
![image](https://user-images.githubusercontent.com/97428873/178210744-06abe5ce-1e71-42f1-817f-561c574b8ad9.png)
获取需要的值在下面图片
![image](https://user-images.githubusercontent.com/97428873/178211113-f1d3440b-b4e6-4fdf-9909-eb50819ff46e.png)
脚本会获取值后会自动添加到配置文件运行脚本，然后删除添加的内容
不过因为大部分KR的频道一天可能会发几个，使用只有日志文件很多都是下面内容
![image](https://user-images.githubusercontent.com/97428873/178212435-4df1433e-ae5d-4e13-a462-582ee9e7c22a.png)
脚本暂时没有完善，可以使用到九月的域名到期

**Comment by dnxbice** [comment]
谢谢大佬指点
