### ISSUE TITLE
日志里显示脚本不存在

### ISSUE THREAD

**Issue by ott4** [XgzK/QL_variable#10]
不清楚这是不是因为我的操作不当导致的，希望大佬解惑
![QQ截图20220721201618](https://user-images.githubusercontent.com/109533228/180212308-6d5f0c95-f4ce-4724-be30-96669b3ebf6c.png)

**Comment by XgzK** [comment]
> 不清楚这是不是因为我的操作不当导致的，希望大佬解惑 ![QQ截图20220721201618](https://user-images.githubusercontent.com/109533228/180212308-6d5f0c95-f4ce-4724-be30-96669b3ebf6c.png)

是因为你没有这个脚本，所以提示你脚本不存在

**Comment by ott4** [comment]
好的，了解了
