### ISSUE TITLE
arm格式报错，exec /bin/sh: exec format error

### ISSUE THREAD

**Issue by Juijote** [XgzK/QL_variable#15]
我ARM机器一直报错格式问题exec /bin/sh: exec format error，不知道是不是镜像编译出错了，AMD机器倒是可以正常运行。

**Comment by XgzK** [comment]
> 我ARM机器一直报错格式问题exec /bin/sh: exec format error，不知道是不是镜像编译出错了，AMD机器倒是可以正常运行。

晚上会修复

**Comment by XgzK** [comment]
> 我ARM机器一直报错格式问题exec /bin/sh: exec format error，不知道是不是镜像编译出错了，AMD机器倒是可以正常运行。

重新试下

**Comment by Juijote** [comment]
> > 我ARM机器一直报错格式问题exec /bin/sh: exec format error，不知道是不是镜像编译出错了，AMD机器倒是可以正常运行。
> 
> 重新试下

现在容器可以运行起来了，但是登录后端填数据，看docker日志发现任务没反应，也试过本地重新构建镜像了还是不行,不知道是不是后端没填对？我是按照以前格式填的。

```
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5008
 * Running on http://192.168.0.22:5008
Press CTRL+C to quit
192.168.0.13 - - [02/Oct/2022 04:52:48] "GET / HTTP/1.1" 200 -
['https://*********', 'iOq-fZH6L_H9', 'HnVW7eNjCCA1hX_qqNzD8W_1', '', '', '', 'on']
192.168.0.13 - - [02/Oct/2022 04:53:07] "POST / HTTP/1.1" 302 -
192.168.0.13 - - [02/Oct/2022 04:53:07] "GET / HTTP/1.1" 200 -
```

**Comment by XgzK** [comment]
> > > 我ARM机器一直报错格式问题exec /bin/sh: exec format error，不知道是不是镜像编译出错了，AMD机器倒是可以正常运行。
> > 
> > 
> > 重新试下
> 
> 现在容器可以运行起来了，但是登录后端填数据，看docker日志发现任务没反应，也试过本地重新构建镜像了还是不行,不知道是不是后端没填对？我是按照以前格式填的，正常显示应该会连接青龙才对？
> 
> 青龙面板版本 v2.14.7 青龙URL试过以下的几种方式在后端连接： 1.代理后的网址，不带端口（容器以前的版本是以这个可以正常运行）； 2.docker同网段内用hostname+端口连接； 3.qlva与青龙都运行在host模式下用 http://127.0.0.1:5700 连接；
> 
> 只能显示以下这些：
> 
> ```
>  * Running on all addresses (0.0.0.0)
>  * Running on http://127.0.0.1:5008
>  * Running on http://192.168.0.22:5008
> Press CTRL+C to quit
> 192.168.0.13 - - [02/Oct/2022 04:52:48] "GET / HTTP/1.1" 200 -
> ['https://*********', 'iOq-fZH6L_H9', 'HnVW7eNjCCA1hX_qqNzD8W_1', '', '', '', 'on']
> 192.168.0.13 - - [02/Oct/2022 04:53:07] "POST / HTTP/1.1" 302 -
> 192.168.0.13 - - [02/Oct/2022 04:53:07] "GET / HTTP/1.1" 200 -
> ```
> 
> 也试过把 http://xgzq.ml:5000/qlcs 填写在api栏也不行。

最快的方法卸载容器和镜像重新

**Comment by Juijote** [comment]
> 最快的方法卸载容器和镜像重新

试过好几次了还是不行；

突然想到，qlva容器默认对于青龙的数据库和配置文件的修改路径是哪个，看新版的conn文件好像不再配置？会不会是默认设置与我的路径不对应，所以连不上？
