### ISSUE TITLE
大佬 能不能获取一下机器人的授权 

### ISSUE THREAD

**Issue by yihanxx** [XgzK/QL_variable#17]
想使用您IP_cistern项目，但是http容器里的授权需要群组内才能获取到授权，请问能否授权一下？

**Comment by XgzK** [comment]
> 想使用您IP_cistern项目，但是http容器里的授权需要群组内才能获取到授权，请问能否授权一下？

只能群里才能获取授权非群内人员就是获得授权也没办法使用
