### ISSUE TITLE
获取不到版本号

### ISSUE THREAD

**Issue by 17huiwei** [XgzK/QL_variable#19]
[2022-11-03 14:12:27,512] [info]- 无法获取版本号,程序无法自动适配,请手动去浏览器查看 青龙IP:端口/api/system 如果返回你青龙版本号请联系开发者修改

我用上面log里面的地址可以看到
{"code":200,"data":{"isInitialized":true,"version":"2.14.9"}}

**Comment by XgzK** [comment]
> [2022-11-03 14:12:27,512] [info]- 无法获取版本号,程序无法自动适配,请手动去浏览器查看 青龙IP:端口/api/system 如果返回你青龙版本号请联系开发者修改
> 
> 我用上面log里面的地址可以看到 {"code":200,"data":{"isInitialized":true,"version":"2.14.9"}}

重启应该就行了，或者不保留配置文件重新填
