### ISSUE TITLE
pip3 install -r requirements.txt运行这一步时出错，然后下面的命令也出错了！

### ISSUE THREAD

**Issue by jackox123** [XgzK/QL_variable#2]
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kza60uh8/logging/

出现这个错误，怎么搞啊？楼主！

**Comment by XgzK** [comment]
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kza60uh8/logging/
> 
> 出现这个错误，怎么搞啊？楼主！

pip3 install logging
运行这个试试

**Comment by jackox123** [comment]
> pip3 install logging

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_xfecgs9/logging/
还是出现这个错误哦！

**Comment by XgzK** [comment]
> > pip3 install logging
> 
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_xfecgs9/logging/ 还是出现这个错误哦！

直接运行 python3 ql_cs.py
如果报错把错误截屏

**Comment by zheng301** [comment]
报错咋解决呀

**Comment by XgzK** [comment]
> 报错咋解决呀

什么错误，要是他这个错误好像python自带，直接执行下一步有报错再截图

**Comment by XgzK** [comment]
> > pip3 install logging
> 
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_xfecgs9/logging/ 还是出现这个错误哦！

跳过执行下一步，看看是否报错，这个好像python自带的依赖

**Comment by zheng301** [comment]
> > > pip3 安装日志
> > 
> > 
> > 命令 "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-_xfecgs9/logging/ 还是出现这个错误哦！
> 
> 执行下一步，看看是否报错，这个蟒蛇自带的依赖

    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-msy7olk5/logging/
[root@VM-8-8-centos ~]# python3 ql_cs.py
Traceback (most recent call last):
  File "ql_cs.py", line 1, in <module>
    from flask_apscheduler import APScheduler
ModuleNotFoundError: No module named 'flask_apscheduler'

**Comment by XgzK** [comment]
> 直接运行程序也不行



> APScheduler

pip3 install Flask-APScheduler
这个好像需要单独安装

**Comment by zheng301** [comment]
> > 直接运行程序也不行
> 
> > AP调度程序
> 
> pip3 install Flask-APScheduler 这个好像需要单独安装

安装完成，然后装依赖或者直接运行程序也报错，难受

**Comment by XgzK** [comment]
> > > 直接运行程序也不行
> > 
> > 
> > > AP调度程序
> > 
> > 
> > pip3 install Flask-APScheduler 这个好像需要单独安装
> 
> 安装完成，然后装依赖或者直接运行程序也报错，难受

还是刚刚提示？

**Comment by zheng301** [comment]
> > > > 直接运行程序也不行
> > > 
> > > 
> > > > AP调度程序
> > > 
> > > 
> > > pip3 install Flask-APScheduler 这个好像需要单独安装
> > 
> > 
> > 安装完成，然后安装依赖或者直接运行程序也报错，难受
> 
> 还是刚刚提示？

对的，还是一样的报错

**Comment by XgzK** [comment]
> pip3 install Flask

pip3 install Flask
加这个要是报错直接截图

**Comment by jaytee11** [comment]
我也遇到了同样的问题
![1](https://user-images.githubusercontent.com/105414352/179209410-dc3c5399-cac8-45b7-a0f4-ae61696b4893.png)

**Comment by XgzK** [comment]
> 我也遇到了同样的问题 ![1](https://user-images.githubusercontent.com/105414352/179209410-dc3c5399-cac8-45b7-a0f4-ae61696b4893.png)

这个不用管logging是内置的直接运行下一步稍后会取消logging
