### ISSUE TITLE
"优先执行的库"到底怎么填写？

### ISSUE THREAD

**Issue by 17huiwei** [XgzK/QL_variable#20]
【优先执行的库 提交格式 task 库名/任意脚本】
提示是这么写的，是否只能填写一个具体的脚本？
但是船长脚本有好多可以运行呀？我只能填写一个么？

**Comment by XgzK** [comment]
> 【优先执行的库 提交格式 task 库名/任意脚本】 提示是这么写的，是否只能填写一个具体的脚本？ 但是船长脚本有好多可以运行呀？我只能填写一个么？
所有脚本优先执行这个库的不是让个别脚本走这个库，吧图片的内容全部复制就像提交后程序会自己处理 

![image](https://user-images.githubusercontent.com/97428873/201176841-1b4bb86e-8fd0-4d1f-8c7f-3b50961c76cd.png)

**Comment by 17huiwei** [comment]
十分感谢老大：）
