### ISSUE TITLE
按照教程操作  出现异常

### ISSUE THREAD

**Issue by kensam0805** [XgzK/QL_variable#21]
[2022-11-14 02:39:59,527] [info]- 异常消息 [ProxyError('404 Not Found')] 触发异常停止10秒
 

群晖本地(无代理)

**Comment by XgzK** [comment]
> [2022-11-14 02:39:59,527] [info]- 异常消息 [ProxyError('404 Not Found')] 触发异常停止10秒
> 
> 群晖本地(无代理)

没有填写机器人tk

**Comment by kensam0805** [comment]
填写TK  发现还是报错   TG机器人：5XXXXXX:xxxxxxxx
