### ISSUE TITLE
应该可以直接在青龙里面task QL_variable-main/ql_cs.py

### ISSUE THREAD

**Issue by fanaruto** [XgzK/QL_variable#3]
![image](https://user-images.githubusercontent.com/45444732/179160725-cd2c97a8-2fcb-4c3f-a9b8-397283c3377b.png)
是不是运行起来就可以了

**Comment by XgzK** [comment]
> 

这种好像没有运行这个有异常信息，会无法运行青龙任务没有获取到青龙ck
没有在容器里面运行过，不清楚会有什么问题，建议放在服务器上方便管理
![image](https://user-images.githubusercontent.com/97428873/179162404-c4af9807-df24-487a-afae-c7743599c22f.png)

**Comment by fanaruto** [comment]
确实，就算正确也显示QL tk错误

**Comment by XgzK** [comment]
> 就算正确也显示QL tk错误

等下测试下放青龙容器试试

**Comment by fanaruto** [comment]
好嘞期待佳音嘿嘿，能直接task方便多 直接在青龙里面装依赖就行

**Comment by XgzK** [comment]
> 好嘞期待佳音嘿嘿，能直接task方便多 直接在青龙里面装依赖就行

如果写到一个文件可以这样，文件太多使用青龙面板拉取会多出很多任务好像
