### ISSUE TITLE
大佬，有新开卡的活动会自动拉库运行吗

### ISSUE THREAD

**Issue by jamesyoung233** [XgzK/QL_variable#6]
大佬，有新开卡的活动会自动拉库运行吗？还有一个就是ql_kill.py拼成了qi_kill.py，运行了一下发现了

**Comment by XgzK** [comment]
> 

暂时知道发京东活动链接的我只知道KingRan521别的不知道还有什么，如果KingRan521里面发的活动链接里面有就会自动运行，你也可以给变量和脚本我添加进去，一般只要这个活动链接有的都会自动运行相应脚本
![image](https://user-images.githubusercontent.com/97428873/179198096-3d7ad17f-b41e-4ff2-8494-a6d17aff0903.png)

**Comment by XgzK** [comment]
> 能监控并自动运行吗？下图这种

你意思是只执行脚本而不添加变量是吗
