### ISSUE TITLE
爬虫脚本爬取频道汇总

### ISSUE THREAD

**Issue by XgzK** [XgzK/QL_variable#9]
KingRan521 == KingRan通知
wondertemple == 共富殿频道
HarbourToulu == 锦鲤偷撸
jdrain  == 甘露殿
fdd_JSB  == 豆豆の垃圾桶(偶尔有)
下面的是准备取消监控的频道
XGZnote(个人的没有京东活动测试用的)
okyydsnb ==  冲鸭 - 万事屋(偶尔可能有)
如果频道管理者有意见会立刻取消监控
正在优化后端爬虫脚本尽量留几个接口让你们自己添加修改脚本和变量(如果有时间和能力完善的情况下)，如果有人要爬虫脚本可以发邮箱，只是因为缺陷比较大，不断完善不方便分享出来，如果有其他频道也可以分享出来

**Comment by zcmi** [comment]
共富殿频道经常会重复发，容易黑号，不知道作者有没有做了什么预防措施

**Comment by XgzK** [comment]
脚本本地去重功能，重复内容不会执行

zcmi ***@***.***> 于 2022年7月21日周四 18:36写道：
